name: Deploy

#Trigger the workflow on push and 
#pull request events on the master branch
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

# Aunthenticates to the server via ssh
# and run out deployment script

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Deploy to Server
       uses: appleboy/ssh-action@master
       with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        pory: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY}}
        script: "cd /var/www/tailwind_props && ./.scripts/deploy.sh"
